#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This is an alist unit test
#
TestName="debug-tags_test"
. scripts/functions
make -C $src/src/tools $TestName

$bin/$TestName
exit $?
