#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
. scripts/functions

if [ $# -ne 0 ]; then
   echo "$@" >> $tmp/dummy_bsmtp.out
fi
while read line ; do
   echo "${line}" >> $tmp/dummy_bsmtp.out
done

exit 0
