#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
. scripts/functions

while test 1 ; do
  read a
  echo "${a}" >> $tmp/dummy_bsmtp.out
  if test $? != 0; then
    exit 0
  fi
done

exit 0
